### ISSUE TITLE
joinConference() - Video is not displaying

### ISSUE THREAD

**Issue by rohit241** [voxeet/web-sdk-sample#3]
Hello team,
I am facing issue related to Voxeet web SDK in my server and i am following this document https://developer.voxeet.com/reference/javascript/reference-javascript/
I am implementing voxeet video API, My issue is 
**When I call joinConference() function my audio and video devices are ready to use or in use but the video is not displaying in the screen and not getting any error in my console** 
and below is my code  

            voxeet.initialize('myConsumerKey', 'myConsumerSecret', {name: 'John Doe'})
          .then((myUserId) => { 
            var conference={};
            var constraints = {audio: true, video: true};
            var conferenceId = '<?php echo 'ITPRWGR'.rand(1000,99999) ?>'; 
            voxeet.joinConference(conferenceId, {constraints: constraints}, conference)
              .then((info) => {
                      voxeet.enumerateVideoDevices()
                      .then((devices) => { 
                      })
                      .catch((e) => {});
                      voxeet.enumerateAudioDevices()
                      .then((devices) => { 
                      })
                      .catch((e) => { });
                      voxeet.selectVideoInput(deviceId, constraints)
                     .then(() => {})
                     .catch((e) => {});
                      voxeet.startVideoForUser(userId, constraints)
                       .then(() => { 
                       });
              })
              .catch((error) => {
              }); 
              })
              .catch((error) => { 
                 alert('An Error has occured, see Error Types');
              }); 

Hoping for the Fast Reply.

**Comment by codlab** [comment]
You have a completely wrong promise implementation. Please check your cascading implementation

**Comment by rohit241** [comment]
What do you mean by "cascading implementation" ?

**Comment by rohit241** [comment]
What do you mean by "cascading implementation" ?

**Comment by Energizz** [comment]
Hello @rohit241 , 

Inside your code, I can see that you use `selectVideoInput` and pass it a `deviceId`
What is the value of this `deviceId` ?
You're trying to select a video input from a deviceId that seems not initialized. 
That's the first point.

However, you can just remove everything inside the promise from the joinConference. Just making joinConference with constraints audio: true and video: true will make you join the conference with audio and video. 
You now need to create you're video tag and attach the stream received from events
participantJoined and participantUpdated
https://developer.voxeet.com/reference/javascript/reference-javascript/
You will see a stream received by this event. 
Feel free to check the sample code from this repository.

If you want, you can also use our toolkit (UI Ready) feel free to follow this link : 
https://github.com/voxeet/voxeet-react-components
Clone and update as your wish :)
