### ISSUE TITLE
Error on MS Edge 15 with voxeet-web-sdk 1.9.5

### ISSUE THREAD

**Issue by Bonias** [voxeet/web-sdk-sample#4]
`voxeet-web-sdk 1.9.5` throws `Unable to get property 'bind' of undefined or null reference` exception in MS Edge 15 (probably also in MS Edge 14 and older versions).

There is no such error when using:

  - MS Edge 15 + voxeet-web-sdk 1.9.4
  - MS Edge 16 + voxeet-web-sdk 1.9.5

**Steps to Reproduce the Problem**

  1. Clone the repo
  2. Change `voxeet-web-sdk` version in the package.json to `1.9.5`
  3. npm install
  4. npm start
  5. Open `https://0.0.0.0:8080/` in MS Edge 15 (you can use www.browserstack.com or www.lambdatest.com)
  6. Push F12 and see error in developer console

See screenshot:
![voxeet-sdk-edge-15-bug](https://user-images.githubusercontent.com/95517/62615488-a1191600-b90d-11e9-9a2e-81f99c15f2bd.png)

**Comment by youssmak** [comment]
Same on Microsoft Edge Dev for macOS
@Energizz any news on this ?

**Comment by popzelife** [comment]
It seems to be linked with this issue: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15960321/

It can be hotfix with this polyfill before loading packages:
```
if (navigator.userAgent.indexOf('Edg\') !== -1) {
                navigator.getDisplayMedia = function() {
                    return navigator.mediaDevices.getUserMedia(arguments)
                };
            }
```

But there's troubles with MediaDevices when trying to share screen `Failed to execute 'getUserMedia' on 'MediaDevices': At least one of audio and video must be requested`

**Comment by FabienLavocat** [comment]
You will find the list of supported web browsers on this web page https://dolby.io/developers/interactivity-apis/client-sdk/articles/supported-client-platforms#web-sdk
