### ISSUE TITLE
TypeScript definition

### ISSUE THREAD

**Issue by guatedude2** [voxeet/web-sdk-sample#6]
`voxeet-web-sdk` currently does not include typings for typescript. It would be really nice to get these in.

I've attached some typings that i've deduced from the sources, granted these probably need to be revised, but its a good start.

[voxeet.d.ts.zip](https://github.com/voxeet/web-sdk-sample/files/5762077/voxeet.d.ts.zip)

**Comment by FabienLavocat** [comment]
Thank you for your message, I will add this request to our backlog.

**Comment by guatedude2** [comment]
Hi @FabienLavocat any progress on this issue?

**Comment by FabienLavocat** [comment]
Hi @guatedude2, yes and I have a good news, we will publish the TypeScript definition in the next patch release that's coming within the next couple of weeks.

**Comment by FabienLavocat** [comment]
@guatedude2 the TypeScript definition is finally available directly when you install the latest version of the voxeet-web-sdk
https://www.npmjs.com/package/@voxeet/voxeet-web-sdk/v/3.1.5

**Comment by guatedude2** [comment]
Amazing!

Alejandro Gonzalez
